icr/urls.py
from django.conf import settings 
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django import views as django_views

from blog.views import blog_homepage
from repository.views import homepage, about, author_create, add_category, add_venue, update_post, arxiv_post, register_request, submit_conference

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name = 'homepage'),
    path('about/', about, name = 'about'),
    path('update_post/<slug>/', update_post, name='update_post'),
    path('author_create/', author_create, name='author_create'),
    path('add_category/', add_category, name='add_category'),
    path('add_venue/', add_venue, name='add_venue'),
    path('blog/', blog_homepage, name='blog_homepage'),
    path('arxiv_post/', arxiv_post, name='arxiv_post'),
    path('register/', register_request, name='register'),
    path('submit_conference/', submit_conference, name='submit_conference'),
    url(r'^jsi18n/$', django_views.i18n.JavaScriptCatalog.as_view(), name='jsi18n'),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

repository/models.py
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.db import models

from embed_video.fields import EmbedVideoField


class Author(models.Model):
    user = models.CharField(max_length=250)
    user_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.user


class Venue(models.Model):
    id = models.AutoField(primary_key=True)
    venue_name = models.CharField(max_length=250)
    year = models.IntegerField()
    venue_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.venue_name + ' ' + str(self.year)


class Category(models.Model):

    title = models.CharField(max_length=250)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Post(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    authors = models.ManyToManyField(Author)
    thumbnail = models.ImageField(blank=True, null=True)
    categories = models.ManyToManyField(Category)
    venue = models.ManyToManyField(Venue, blank=True, default='')
    citation = models.URLField(blank=True, null=True)
    pdf = models.URLField(blank=True, null=True)
    supplement = models.URLField(blank=True, null=True)
    slides = models.URLField(blank=True, null=True)
    poster = models.URLField(blank=True, null=True)
    code = models.URLField(blank=True, null=True)
    video = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Conference(models.Model):
    conference_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250, unique=True)
    link = models.URLField(max_length=5000)
    location = models.CharField(max_length=250)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.name

repository/views.py
import os
import yaml
import json
import requests
import urllib3

from .models import Post
from dotenv import load_dotenv
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.contrib.auth import login
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .models import Conference
from .forms import PostForm, AuthorForm, VenueForm, CategoryForm, ArxivForm, NewUserForm, ConferenceForm
from .utils import generate_qmd_header, generate_page_content, create_push_request, generate_qmd_header_for_arxiv, scrap_data_from_arxiv, get_conference_information, generate_headers_for_conference_calendar, generate_content_for_conference_calendar


@login_required
def homepage(request):

    load_dotenv()

    if request.method == 'POST':
        filled_form = PostForm(request.POST)

        if filled_form.is_valid():
            filled_form.save()
            form_data = filled_form.cleaned_data

            content = {}
            content = generate_qmd_header(content, form_data)

            folder_name = slugify(content.get('title', ''))

            current_path = os.getcwd()
            
            current_path = current_path + f'/icr_frontend/content/{folder_name}/'

            file_path = f'{current_path}index.qmd'

            if not os.path.exists(current_path):
                os.makedirs(current_path)

            with open(file_path, 'w+') as fp:
                fp.write('---\n')
                yaml.dump(content, fp)
                fp.write('\n---')

            generate_page_content(content, file_path)

            repo = 'icr'

            try:
                create_push_request(file_path, folder_name, repo)
            except Exception as ex:
                messages.error(
                    request,
                    "We are experiencing some problems when fetching when communication with github. Please Try again later.")
                return redirect("")

            context = {
                'folder_name': folder_name,
                'form': filled_form
            }

            print(context)
        else:
            messages.error(request, filled_form.errors.as_data().title)

        return render(request, 'repository/submission.html', context)
    else:
        filled_form = PostForm()
        return render(
            request,
            'repository/new_post.html',
            context={
                'form': filled_form})


def about(request):
    return render(request, 'repository/about_page.html')


def author_create(request):

    if request.method == 'GET':
        form = AuthorForm()
        context = {'form': form}
        return render(
            request,
            'repository/create_author.html',
            context=context)

    form = AuthorForm(request.POST)

    if form.is_valid():
        author_instance = form.save()
        instance = serializers.serialize('json', [author_instance, ])
        return JsonResponse({"instance": instance}, status=200)
    else:
        messages.error(request, form.errors.as_data().title)


def add_venue(request):

    if request.method == 'GET':
        form = VenueForm()
        context = {'form': form}
        return render(request, 'repository/add_venue.html', context=context)

    form = VenueForm(request.POST)

    if form.is_valid():
        venue_instance = form.save()
        instance = serializers.serialize('json', [venue_instance, ])
        return JsonResponse({"instance": instance}, status=200)
    else:
        messages.error(request, form.errors.as_data().title)


def add_category(request):

    if request.method == 'GET':
        form = CategoryForm()
        context = {'form': form}
        return render(request, 'repository/add_category.html', context=context)

    form = CategoryForm(request.POST)
    if form.is_valid():
        category_instance = form.save()
        instance = serializers.serialize('json', [category_instance, ])
        return JsonResponse({"instance": instance}, status=200)
    else:
        messages.error(request, form.errors.as_data().title)


def update_post(request, slug):

    context = {}

    post = get_object_or_404(Post, slug=slug)

    form = PostForm(request.POST or None, instance=post)

    if request.method == 'GET':
        context = {'form': form}
        return render(request, "repository/update_post.html", context=context)

    if form.is_valid():
        post_instance = Post.objects.get(slug=slug)
        form = PostForm(request.POST, instance=post)
        form.save()
        instance = serializers.serialize('json', [post_instance, ])
        return JsonResponse({"instance": instance}, status=200)
    else:
        messages.error(request, form.errors.as_data().title)
    

def arxiv_post(request):

    load_dotenv()

    if request.method == 'POST':
        context = {}

        enviroment_name = os.getenv('ENV_NAME')
        filled_form = ArxivForm(request.POST)

        if filled_form.is_valid():
            #filled_form.save()
            form_data = filled_form.cleaned_data

            url = form_data.get('link', '')

            try:
                data = scrap_data_from_arxiv(url)
            except Exception as ex:
                messages.error(
                    request,
                    "We are experiencing some problems when fetching information from Arxiv. Please Try again later.")
                return redirect("arxiv_post")

            content = generate_qmd_header_for_arxiv(data)

            folder_name = slugify(content.get('title', ''))

            current_path = os.getcwd()

            current_path = current_path + f'/icr_frontend/content/{folder_name}/'
            file_path = f'{current_path}index.qmd'

            if not os.path.exists(current_path):
                os.makedirs(current_path)

            with open(file_path, 'w+') as fp:
                fp.write('---\n')
                yaml.dump(content, fp)
                fp.write('\n---')

            generate_page_content(content, file_path)

            try:
                create_push_request(file_path, folder_name)
            except Exception as ex:
                messages.error(
                    request,
                    "We are experiencing some problems when fetching when communication with github. Please Try again later.")
                return redirect("arxiv_post")

            context = {
                'folder_name': folder_name,
                'form': filled_form
            }

            return render(request, 'repository/submission.html', context=context)
        
        messages.error(request, filled_form.errors.as_data().title)

    form = ArxivForm()
    context = {
        'form': form
    }
    return render(request, 'repository/arxiv_post.html', context=context)


def email_check(user):
    if user.is_authenticated:
        return user.email.endswith('@bristol.ac.uk')
    print('Fudeu')
    return False


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            email = form_data['email']

            if email.endswith('@bristol.ac.uk'):
                user = form.save()
                login(request, user)
                messages.success(request, "Registration successfull.")
                return redirect("homepage")
            messages.error(
                request, "Email should belong to @bristol.ac.uk domain.")
            return render(
                request,
                'registration/register.html',
                context={
                    "register_form": form,
                    "message": "Email should belong to @bristol.ac.uk domain."})

        messages.error(
            request,
            "Uncessfull registration. Invalid information.")

    form = NewUserForm()
    return render(
        request,
        'registration/register.html',
        context={
            "register_form": form})

@login_required
def submit_conference(request):

    if request.method == 'POST':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':    
            url = request.body.decode('UTF-8')
            if url != '':
                response = get_conference_information(url)

                return JsonResponse(response, status=200, safe=False)  
            else:
                response = {
                    'title': '',
                    'dates': [['', '']],
                    'places': '',

                }
                return JsonResponse(response, status=200, safe=False)
        
        form = ConferenceForm(request.POST)

        if form.is_valid():
            form.save()
            
            conferences = Conference.objects.order_by('start_date')

            current_path = os.getcwd()
            
            filepath = current_path + f'/conference_calendar/index.qmd'

            generate_headers_for_conference_calendar(filepath=filepath)

            generate_content_for_conference_calendar(conference_objects=conferences, filepath=filepath)

            repo = 'conference_calendar'

            create_push_request(file_path=filepath, folder_name='', repo=repo)

    form = ConferenceForm()

    context = {
            "form": form
        }

    return render(
            request,
            'repository/submit_conference.html',
            context=context
        )

repository/templates/repository/about_page.html
{% extends 'repository/base.html' %}
{% block content %}

<div class="container">
    <p class="blockquote text-center">This is a unified authoring platform that makes it easy (for reasonably computer-savvy users) to make academic content in all its forms available on the web in a coherent and easily maintained way,
        increasing both presence and reach of the work going on in an AI research group or CDT.
    </p>
</div>

{% endblock content %}

repository/templates/repository/add_category.html
{% block content %}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header bg-dark text-white">
            <h1 class="modal-title fs-5"  id="addCategoryModalLabel"> Add Category </h1>
        </div>
        <form id="addCategoryForm" action="{% url 'add_category' %}" method="post" >
            <div class="modal-body">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input class="mt-3" type="submit" value="Submit" />
            </div>
        </form>

    </div>
</div>
{% endblock content %}

repository/templates/repository/add_venue.html
{% block content %}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header bg-dark text-white">
            <h1 class="modal-title fs-5 "  id="addVenueModalLabel"> Add Venue </h1>
        </div>
        <form id="addVenueForm" action="{% url 'add_venue' %}" method="post" >
            <div class="modal-body">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input class="mt-3" type="submit" value="Submit" />
            </div>
        </form>

    </div>
</div>
{% endblock content %}

repository/templates/repository/arxiv_post.html
{% extends 'repository/base.html' %} 
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h1>New Post</h1>
        <form action="{% url 'arxiv_post' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

repository/templates/repository/base.html
<!doctype html>
<html>
{% load static %}
<head>
    <title>Interactive Content Repository</title>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Interactive Content Repository</title>

    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
      
    <script>

            $(document).ready(function () {
                let my_modal = $("#addAuthorModal");
                const url_form = "author_create/";
                $("#addAuthor a").click(function (e) {
                    e.preventDefault();
                    my_modal.load(url_form, function () {
                        my_modal.modal("show"); // Open Modal
                        $("#addAuthorForm").submit(function (e) {
                            e.preventDefault(); // Cancel the default action
                            $.ajax({
                                method: "POST",
                                data: $(this).serialize(),
                                dataType: "json",
                                url: "author_create/",
                                success: function (response) {
                                    my_modal.modal('hide');
                                    window.location.reload();
                                },
                                error: function (response) {
                                    console.log(response);
                                    my_modal.modal('hide');
                                },
                            });
                        });
                    });
                });
            });

            $(document).ready(function () {
                let my_modal = $("#addCategoryModal");
                const url_form = "add_category/";
                $("#addCategory a").click(function (e) {
                    e.preventDefault();
                    my_modal.load(url_form, function () {
                        my_modal.modal("show"); // Open Modal
                        $("#addCategoryForm").submit(function (e) {
                            e.preventDefault(); // Cancel the default action
                            $.ajax({
                                method: "POST",
                                data: $(this).serialize(),
                                dataType: "json",
                                url: "add_category/",
                                success: function (response) {
                                    my_modal.modal('hide');
                                    window.location.reload();
                                },
                                error: function (response) {
                                    console.log(response);
                                    my_modal.modal('hide');
                                },
                            });
                        });
                    });
                });
            });

            $(document).ready(function () {
                let my_modal = $("#addVenueModal");
                const url_form = "add_venue/";
                $("#addVenue a").click(function (e) {
                    e.preventDefault();
                    my_modal.load(url_form, function () {
                        my_modal.modal("show"); // Open Modal
                        $("#addVenueForm").submit(function (e) {
                            e.preventDefault(); // Cancel the default action
                            $.ajax({
                                method: "POST",
                                data: $(this).serialize(),
                                dataType: "json",
                                url: "add_venue/",
                                success: function (response) {
                                    my_modal.modal('hide');
                                    window.location.reload();
                                },
                                error: function (response) {
                                    console.log(response);
                                    my_modal.modal('hide');
                                },
                            });
                        });
                    });
                });
            });

            $(document).ready(function () {
                let my_modal = $("#addVenueModal");
                const url_form = "/update_post/{{ post.slug }}";
                data = { 'slug': '{{ post.slug }}' }
                $("#updatePost a").click(function (e) {
                    e.preventDefault();
                    my_modal.load(url_form, function () {
                        my_modal.modal("show"); // Open Modal
                        $("#updatePostForm").submit(function (e) {
                            e.preventDefault(); // Cancel the default action
                            $.ajax({
                                method: "POST",
                                data: $(this).serialize(),
                                dataType: "json",
                                url: "/update_post/{{ post.slug }}/",
                                success: function (response) {
                                    my_modal.modal('hide');
                                    window.location.reload();
                                },
                                error: function (response) {
                                    console.log(response);
                                    my_modal.modal('hide');
                                },
                            });
                        });
                    });
                });
            });
            
            function getCookie(c_name)
            {
                if (document.cookie.length > 0)
                {
                    c_start = document.cookie.indexOf(c_name + "=");
                    if (c_start != -1)
                    {
                        c_start = c_start + c_name.length + 1;
                        c_end = document.cookie.indexOf(";", c_start);
                        if (c_end == -1) c_end = document.cookie.length;
                        return unescape(document.cookie.substring(c_start,c_end));
                    }
                }
                return "";
            }

            $(document).ready(function (){
                $(".conference_link").change(function (e) {
                    link = $(this).val()
                    console.log(link);
                    e.preventDefault();
                    $.ajaxSetup({
                        headers: { "X-CSRFToken": getCookie("csrftoken") }
                    });
                    $.ajax({
                                method: "POST",    
                                data: link,
                                url: "/submit_conference/",
                                contentType: 'application/json; charset=UTF-8',
                                success: function (response) {
                                    console.log(response);
                                    $("#id_name").val(response['title']);
                                    $("#id_start_date").val(response['dates'][0][0]);
                                    $("#id_end_date").val(response['dates'][0][1]);
                                    $("#id_location").val(response['places'][0]);
                                },
                                error: function (request, response) {
                                    console.log(response)
                                },
                    });

                });
            });

    </script>
</head>

<body>
    <script src="{% static 'modal_forms/js/script.js' %}"></script>
    <input type="hidden" id="mf-url-base" value="/mf-data">
    
    {% if invalid_form %}
    <input
        type="hidden"
        id="mf-error"
        data-mf_name="{{ invalid_form.name }}"
        data-mf_pk="{{ invalid_form.pk }}"
    >
    {% endif %}
    
    
    
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'homepage' %}">Interactive Content Rerpository</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_homepage' %}">Blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'submit_conference' %}">Conferences</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'register' %}?next={{ request.path }}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Interactive Content Repository </h3>
                        <p class="text-light">
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    {% include 'repository/modals.html' %}
    {% include 'repository/messages.html' %}
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
    <!-- Footer -->

    <footer class="py-3 bg-grey">

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>

</html>

repository/templates/repository/homepage.html
{% extends "repository/base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>


<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
            <div class="card mb-4">
                <h3 class="card-header bg-dark text-white">{{ post.title }}</h3>
                <div class="card-body">
                    <p class="card-text text-muted h6"> {{ post.timestamp}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'repository/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

repository/templates/repository/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

repository/templates/repository/modals.html
<!doctype html>
{% block content %}
<div class="modal fade" id="addAuthorModal" tabindex="-1" aria-labelledby="addAuthorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        

        </div>
    </div>
</div>

<div class="modal fade" id="addCategoryModal" tabindex="-1" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        

        </div>
    </div>
</div>

<div class="modal fade" id="addVenueModal" tabindex="-1" aria-labelledby="addVenueModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        

        </div>
    </div>
</div>

<div class="modal fade" id="updatePostModal" tabindex="-1" aria-labelledby="updatePostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        

        </div>
    </div>
</div>

{% endblock content %}

repository/templates/repository/post.html
{% extends 'repository/base.html' %} 
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h2>{% block title %} {{ post.title }} {% endblock title %}</h2>
        <h3>Tldr</h3>
        <div id="updatePost" class="form-group mr-5" style="text-align:right">
          <a class="btn btn-primary btn-sm pull-right"  data-bs-toggle="modal" data-bs-target="#updatePostModal" >Edit</a>
        </div>
        <p class="card-text ">{{ post.overview | safe }}</p>
        <br>
        <h3>Paper authors</h3>
          {% for author in post.authors.all %}  
            <a class="card-text" href={{ author.user_url }}>{{ author.user }}</a>
            <br>
          {% endfor %}

        {% if post.venue.venue_name %}
        <h3>Venue</h3>
          <a href= {{ post.venue.venue_url }} >{{ post.venue.venue_name }} {{ post.venue.year }}</a>
          <br>
        {% endif %}

        {% if post.video %}  
        <h3>Video</h3>
          <iframe width="560" height="315" src={{ post.video }} frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          <br>
        {% endif %}

        <h3>More resources</h3>
          
          {% if post.citation %}
            <a  href={{ post.citation }}> 
              <img  src="https://img.shields.io/badge/citation-9cf?style=flat.svg">  
            </a>
          {% endif %}

          {% if post.supplement %}
            <a  href={{ post.supplement }}> 
              <img  src="https://img.shields.io/badge/supplement-yellowgreen?style=flat">  
            </a>
          {% endif %}

          {% if post.pdf %}
            <a  href={{ post.pdf }}> 
              <img  src="https://img.shields.io/badge/PDF-green?style=flat">  
            </a>
          {% endif %}

          {% if post.slides %}
            <a  href={{ post.slides }}> 
              <img  src="https://img.shields.io/badge/slides-ff69b4?style=flat">  
            </a>
          {% endif %}

          {% if post.poster %}
            <a  href={{ post.poster }}> 
              <img  src="https://img.shields.io/badge/poster-yellow?style=flat">  
            </a>
          {% endif %}

          {% if post.code %}
            <a  href={{ post.code }}> 
              <img  src="https://img.shields.io/badge/code-blue?style=flat">  
            </a>
          {% endif %}

      </div>
    </div>
    {% block sidebar %} {% include 'repository/sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}